package org.university.payment_for_utilities.repositories.service_information_institutions;

import org.springframework.stereotype.Repository;
import org.university.payment_for_utilities.domains.service_information_institutions.UnitMeasurement;
import org.university.payment_for_utilities.repositories.TableSearcherRepository;

@Repository
public interface UnitMeasurementRepository extends TableSearcherRepository<UnitMeasurement> {
}
